name = "cluster_module"
uuid = "739d8b47-37ef-4f4d-be45-fc32f9aaf4c6"
authors = ["Ali Ghorashi <aligho@mit.edu>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
